[package]
name = "tinykv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
capnp = "0.14"
capnp-rpc = "0.14"

[build-dependencies]
capnpc = "0.14"
